hyperledger/identus-edge-agent-sdk-kmp

atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/prismagent/PrismAgent.kt
sampleapp/src/main/java/io/iohk/atala/prism/sampleapp/Sdk.kt
sampleapp/src/main/java/io/iohk/atala/prism/sampleapp/ui/agent/AgentFragment.kt
sampleapp/src/main/java/io/iohk/atala/prism/sampleapp/ui/agent/AgentViewModel.kt
sampleapp/src/main/res/layout/fragment_agent.xml

Add an edit text to update the mediator DID from the UI of sample app.

feat: mediator DID can be updated from sample app UI

---

atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/prismagent/PrismAgent.kt
sampleapp/src/main/java/io/iohk/atala/prism/sampleapp/SampleApp.kt
sampleapp/src/main/java/io/iohk/atala/prism/sampleapp/Sdk.kt
sampleapp/src/main/java/io/iohk/atala/prism/sampleapp/ui/agent/AgentViewModel.kt
sampleapp/src/main/java/io/iohk/atala/prism/sampleapp/ui/contacts/ContactsViewModel.kt
sampleapp/src/main/java/io/iohk/atala/prism/sampleapp/ui/credentials/CredentialsAdapter.kt
sampleapp/src/main/java/io/iohk/atala/prism/sampleapp/ui/credentials/CredentialsViewModel.kt
sampleapp/src/main/java/io/iohk/atala/prism/sampleapp/ui/dids/DIDsViewModel.kt
sampleapp/src/main/java/io/iohk/atala/prism/sampleapp/ui/main/MainActivity.kt
sampleapp/src/main/java/io/iohk/atala/prism/sampleapp/ui/main/MainViewModel.kt
sampleapp/src/main/java/io/iohk/atala/prism/sampleapp/ui/messages/MessagesViewModel.kt

fix: fixes demo app fetching job

---

.github/workflows/e2e-tests.yml

ci: fix typo in e2e workflow

---

atala-prism-sdk/build.gradle.kts
build.gradle.kts

Update anoncreds-kmp to the latest version and change it's source to the new repo.

build: Update anoncreds-kmp to the latest version and change it's source

---

atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/pollux/PolluxImpl.kt
atala-prism-sdk/src/commonTest/kotlin/io/iohk/atala/prism/walletsdk/pollux/PolluxImplTest.kt

This PR updates a piece of the logic to `getSchema` to support the latest changes to ZKP verification.
* [] Features (non-breaking change which adds functionality)

refactor(AnonCred): refactor get getSchema method in PolluxImpl

---

atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/castor/CastorImpl.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/castor/shared/CastorShared.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/domain/models/Errors.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/mercury/MercuryImpl.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/mercury/resolvers/DIDCommWrapper.kt

Fix crash when body is empty string
Fixes [ATL-4811]
[ATL-4811]: https://input-output.atlassian.net/browse/ATL-4811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

fix(DIDCommWrapper): Crash when body is empty string

---

.github/workflows/e2e-tests.yml

test: updates java version to 17 for e2e

---

.releaserc.yml

ci: update release

---

README.md
atala-prism-sdk/build.gradle.kts
build.gradle.kts

Publish to Maven central instead of GitHub

chore: Update to publish to maven central

---

build.gradle.kts

chore: update CI script

---

tests/end-to-end/build.gradle.kts
tests/end-to-end/src/test/kotlin/io/iohk/atala/prism/configuration/Environment.kt
tests/end-to-end/src/test/kotlin/io/iohk/atala/prism/models/JwtSchema.kt

test: updates client and fixes endpoint

---

tests/end-to-end/build.gradle.kts

chore: matches e2e sdk version to local publication

---

.github/workflows/release.yml

fix: adds env var for maven central publication

---

.github/workflows/release.yml

fix: release pipeline variable

---

atala-prism-sdk/build.gradle.kts

fix for publishing to maven central

ci: fix for publishing to maven central

---

.github/workflows/release.yml

ci: add missing env variable

---

.github/workflows/e2e-tests.yml
CHANGELOG.md
gradle.properties
tests/end-to-end/build.gradle.kts

PR to update the files generated in the builds

chore: update release files

---

atala-prism-sdk/build.gradle.kts

fix tasks dependency for e2e tests

chore: fix tasks dependency for e2e tests

---

.github/CODEOWNERS
.github/PULL_REQUEST_TEMPLATE.md

- Code owners: the content editor will be automatically added to any PR related to markdown files
- Code owners: update by adding Todor Kolev (still not a member it seems though)
- Pull request template: add the link to the contributing guideline
- [] My PR is free of third-party dependencies that don't comply with the [Allowlist](https://toc.hyperledger.org/governing-documents/allowed-third-party-license-policy.html#approved-licenses-for-allowlist)
- [] I have added tests that prove my fix is effective or that my feature works

docs: update code owners and link contributing guidelines

---

atala-prism-sdk/build.gradle.kts
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/prismagent/ConnectionManager.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/prismagent/PrismAgent.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/prismagent/mediation/BasicMediatorHandler.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/prismagent/mediation/MediationHandler.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/prismagent/protocols/ProtocolType.kt
atala-prism-sdk/src/commonTest/kotlin/io/iohk/atala/prism/walletsdk/prismagent/ConnectionManagerTest.kt
atala-prism-sdk/src/commonTest/kotlin/io/iohk/atala/prism/walletsdk/prismagent/MediationHandlerMock.kt
sampleapp/src/main/res/values/strings.xml

This PR adds support to the KMM repo for mediator live mode which uses websockets.
- [] I have made corresponding changes to the documentation

feat: support for mediator live mode (websocket)

---

tests/end-to-end/.gitignore
tests/end-to-end/build.gradle.kts
tests/end-to-end/src/test/kotlin/io/iohk/atala/prism/TestSuite.kt
tests/end-to-end/src/test/kotlin/io/iohk/atala/prism/configuration/Environment.kt
tests/end-to-end/src/test/kotlin/io/iohk/atala/prism/steps/CloudAgentSteps.kt
tests/end-to-end/src/test/kotlin/io/iohk/atala/prism/steps/EdgeAgentSteps.kt
tests/end-to-end/src/test/kotlin/io/iohk/atala/prism/utils/Keys.kt
tests/end-to-end/src/test/kotlin/io/iohk/atala/prism/utils/Utils.kt
tests/end-to-end/src/test/kotlin/io/iohk/atala/prism/workflow/CloudAgentWorkflow.kt
tests/end-to-end/src/test/resources/features/connection/CreateConnection.feature
tests/end-to-end/src/test/resources/features/credential/Anoncred.feature
tests/end-to-end/src/test/resources/features/credential/Credential.feature
tests/end-to-end/src/test/resources/features/present-proof/AnoncredPresentProof.feature
tests/end-to-end/src/test/resources/features/present-proof/PresentProof.feature

Adds test scenario for zkp presentation flow happy path

test: zkp presentation flow

---

README.md
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/castor/did/prismdid/PrismDIDPublicKey.kt

Changes based on a second review from @mkbreuningIOHK with @hamada147 after the renaming from Atala PRISM Wallet SDK KMM to Edge Agent SDK KMP

docs: Update README.md

---

edge-agent-sdk/docs/examples/BackupAndRestore.md
edge-agent-sdk/docs/examples/JWTRevocationVerification.md
edge-agent-sdk/docs/examples/SDKVerification.md

Added code examples for the new features added recently. Back up and restore, JWT revocation verification and SDK verification across platforms.

docs: add code examples of new features

---

.github/workflows/build-and-test.yml
.github/workflows/e2e-tests.yml
.github/workflows/lint-pr.yml
.github/workflows/release-documentation.yml
.github/workflows/release.yml
build.gradle.kts
package.json

This PR adds the proper config for the publishing process to hyperledger maven following the work @yshyn-iohk did on Apollo.

chore: update the publishing process for hyperledger

---

edge-agent-sdk/docs/examples/SDKVerification.md

Update documentation examples of SDK verification to include Anoncreds.

docs: update SDK verification examples

---

CONTRIBUTING.md

Summarize the changes you're submitting in a few sentences, including Jira ticket ATL-xxxx if applicable.
Link to any discussion, related issues and bug reports to give the context to help the reviewer understand the PR.
Link to existing ADR (Architecture Decision Record), if any. If relevant, describe other approaches explored and the selected approach. Documenting why the methods were not selected will create a knowledge base for future reference, helping prevent others from revisiting less optimal ideas.

chore: update CONTRIBUTING.md links

---

.github/workflows/release.yml
build.gradle.kts

fix: release 4.0

---

tests/end-to-end/build.gradle.kts

Fixes environment variable for ghcr auth

test: fixes ghcr auth

---

.github/workflows/e2e-tests.yml

chore: update variables
