hyperledger/identus-edge-agent-sdk-kmp

atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/apollo/ApolloImpl.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/domain/buildingblocks/Apollo.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/domain/models/Errors.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/domain/models/keyManagement/ExportableImportableKey.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/domain/models/keyManagement/KeyRestoration.kt
atala-prism-sdk/src/commonTest/kotlin/io/iohk/atala/prism/walletsdk/apollo/ApolloTests.kt
atala-prism-sdk/src/commonTest/kotlin/io/iohk/atala/prism/walletsdk/castor/ApolloMock.kt
atala-prism-sdk/src/commonTest/kotlin/io/iohk/atala/prism/walletsdk/prismagent/ApolloMock.kt

Implements KeyRestoration inside apollo. This gives us a way to restore a StorableKey into a Public/Private key.

feat: KeyRestoration

---

.github/workflows/e2e-tests.yml
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/apollo/ApolloImpl.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/apollo/utils/Secp256k1PrivateKey.kt
atala-prism-sdk/src/commonTest/kotlin/io/iohk/atala/prism/walletsdk/apollo/ApolloTests.kt

This PR includes a DerivableKey interface and Secp256k1 implements it to make it derivable.

feat: implement derivableKey an include it into Secp256k1PrivateKey

---

atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/castor/CastorImpl.kt

This PR fixes a cast that would never succeed, casting a public key into key pair.

fix: wrong casting KeyPair instead of PublicKey

---

.github/PULL_REQUEST_TEMPLATE.md

This PR is to update to this PR template:
Update the PR template to the one that was agreed by the IO tribe and that will be applicable to all related repositories, this one included. 
- [] I have commented my code, particularly in hard-to-understand areas
- [] I have added tests that prove my fix is effective or that my feature works

docs: add a PR template

---

atala-prism-sdk/src/androidInstrumentedTest/kotlin/io/iohk/atala/prism/walletsdk/prismagent/AnoncredsTests.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/domain/buildingblocks/Pluto.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/domain/buildingblocks/Pollux.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/domain/models/Credential.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/domain/models/StorableCredential.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/pluto/CredentialRecovery.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/pluto/PlutoImpl.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/pollux/PolluxImpl.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/pollux/models/AnonCredential.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/pollux/models/JWTCredential.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/pollux/models/W3CCredential.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/prismagent/ConnectionManager.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/prismagent/PrismAgent.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/prismagent/protocols/ProtocolType.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/prismagent/protocols/revocation/RevocationNotification.kt
atala-prism-sdk/src/commonMain/sqldelight/io/iohk/atala/prism/walletsdk/pluto/data/StorableCredential.sq
atala-prism-sdk/src/commonTest/kotlin/io/iohk/atala/prism/walletsdk/mercury/PlutoMock.kt
atala-prism-sdk/src/commonTest/kotlin/io/iohk/atala/prism/walletsdk/prismagent/ConnectionManagerTest.kt
atala-prism-sdk/src/commonTest/kotlin/io/iohk/atala/prism/walletsdk/prismagent/PlutoMock.kt
atala-prism-sdk/src/commonTest/kotlin/io/iohk/atala/prism/walletsdk/prismagent/PolluxMock.kt
atala-prism-sdk/src/commonTest/kotlin/io/iohk/atala/prism/walletsdk/prismagent/PrismAgentTests.kt
sampleapp/src/main/java/io/iohk/atala/prism/sampleapp/ui/credentials/CredentialsAdapter.kt
sampleapp/src/main/java/io/iohk/atala/prism/sampleapp/ui/credentials/CredentialsViewModel.kt
sampleapp/src/main/java/io/iohk/atala/prism/sampleapp/ui/messages/MessagesFragment.kt
sampleapp/src/main/java/io/iohk/atala/prism/sampleapp/ui/messages/MessagesViewModel.kt
sampleapp/src/main/res/layout/placeholder_credential.xml
sampleapp/src/main/res/values/strings.xml

This PR adds support for revocation messages and a revocation mechanism to update the local db accordingly.
There is also a new method on the prism agent `observeRevokedCredentials` to get notified when a credential is revoked.

feat: revocation notification event

---

atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/prismagent/ConnectionManager.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/prismagent/PrismAgent.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/prismagent/helpers/AgentOptions.kt
atala-prism-sdk/src/commonTest/kotlin/io/iohk/atala/prism/walletsdk/prismagent/ConnectionManagerTest.kt
atala-prism-sdk/src/commonTest/kotlin/io/iohk/atala/prism/walletsdk/prismagent/PrismAgentTests.kt
sampleapp/src/main/java/io/iohk/atala/prism/sampleapp/Sdk.kt

This PR adds logic to make mediator live mode (websockets communication) an experimental feature and users can opt in/out when instantiating the SDK.

feat: experimental opt-in for mediator live mode

---

atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/prismagent/ConnectionManager.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/prismagent/PrismAgent.kt
atala-prism-sdk/src/commonMain/kotlin/io/iohk/atala/prism/walletsdk/prismagent/helpers/AgentOptions.kt

This PR makes the new addition `AgentOptions` a non-breaking change my including a default constructor parameter to the prism agent. It also includes missing documentation for [PR-150](https://github.com/input-output-hk/atala-prism-wallet-sdk-kmm/pull/150)

refactor: agent options non-breaking change

---

edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/pluto/PlutoImpl.kt

Revert back changes made to how credentials all pulled. That change was probably added to test UI and forgot to take back before merging.

fix: e2e test broken after pull credential changed based on validUntil

---

edge-agent-sdk/build.gradle.kts
edge-agent-sdk/src/androidInstrumentedTest/kotlin/org/hyperledger/identus/walletsdk/edgeagent/AndroidIgnore.android.kt
edge-agent-sdk/src/androidInstrumentedTest/kotlin/org/hyperledger/identus/walletsdk/edgeagent/AnoncredsTests.kt

AnonCred Android instruments tests

chore: AnonCred linting

---

tests/end-to-end/src/test/kotlin/org/hyperledger/identus/walletsdk/abilities/UseWalletSdk.kt
tests/end-to-end/src/test/kotlin/org/hyperledger/identus/walletsdk/steps/CloudAgentSteps.kt
tests/end-to-end/src/test/kotlin/org/hyperledger/identus/walletsdk/steps/EdgeAgentSteps.kt
tests/end-to-end/src/test/kotlin/org/hyperledger/identus/walletsdk/workflow/CloudAgentWorkflow.kt
tests/end-to-end/src/test/kotlin/org/hyperledger/identus/walletsdk/workflow/EdgeAgentWorkflow.kt
tests/end-to-end/src/test/resources/features/credential/RevokeJWT.feature
tests/end-to-end/src/test/resources/features/present-proof/JWTPresentProof.feature

https://input-output.atlassian.net/browse/ATL-6590
- Added test feature and implementation to cover happy case for JWT revocation
- Changed wording around "credential" to differentiate between JWT and AnonCred
- Broke down some in-line statements for easier (to me) debugging

test: Adding happy path validation for JWT revocation

---

edge-agent-sdk/src/androidMain/kotlin/org/hyperledger/identus/walletsdk/pluto/data/DbConnectionImpl.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/pluto/PlutoImpl.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/pluto/data/DbConnectionImpl.kt
edge-agent-sdk/src/jvmMain/kotlin/org/hyperledger/identus/walletsdk/pluto/data/DbConnectionImpl.kt
sampleapp/build.gradle.kts
sampleapp/src/main/java/org/hyperledger/identus/walletsdk/sampleapp/Sdk.kt

Signed-off-by: Cristian G <cristian.castro@iohk.io>
This PR provides the DbConnection as an interface for the end to end tests to use a custom DbConnection to use in memory db.

fix: DbConnection cannot be extended

---

edge-agent-sdk/build.gradle.kts
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/edgeagent/EdgeAgent.kt
edge-agent-sdk/src/commonTest/kotlin/org/hyperledger/identus/walletsdk/edgeagent/EdgeAgentTests.kt

Increase code coverage for edge agent. 
This PR is for ticket:
https://input-output.atlassian.net/browse/ATL-7370

chore: increse code coverage

---

edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/domain/buildingblocks/Pluto.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/edgeagent/EdgeAgent.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/pluto/BackupVersion.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/pluto/PlutoBackupTask.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/pluto/PlutoImpl.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/pluto/PlutoRestoreTask.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/pluto/models/DidKeyLink.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/pluto/models/backup/BackupV0_0_1.kt
edge-agent-sdk/src/commonMain/sqldelight/org/hyperledger/identus/walletsdk/pluto/data/DIDKeyLink.sq
edge-agent-sdk/src/commonTest/kotlin/org/hyperledger/identus/walletsdk/edgeagent/EdgeAgentTests.kt
edge-agent-sdk/src/commonTest/kotlin/org/hyperledger/identus/walletsdk/edgeagent/PlutoMock.kt
edge-agent-sdk/src/commonTest/kotlin/org/hyperledger/identus/walletsdk/mercury/PlutoMock.kt
edge-agent-sdk/src/commonTest/kotlin/org/hyperledger/identus/walletsdk/pluto/BackupRestorationTests.kt
edge-agent-sdk/src/commonTest/kotlin/org/hyperledger/identus/walletsdk/pluto/PlutoImplTest.kt

This PR increases the number of unit tests to improve the code coverage.

chore: increase test coverage

---

build.gradle.kts
edge-agent-sdk/build.gradle.kts
edge-agent-sdk/src/androidInstrumentedTest/kotlin/org/hyperledger/identus/walletsdk/edgeagent/AnoncredsTests.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/domain/buildingblocks/Pollux.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/edgeagent/EdgeAgent.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/pollux/PolluxImpl.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/pollux/models/AnonCredential.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/pollux/models/CredentialRequestMeta.kt
edge-agent-sdk/src/commonTest/kotlin/org/hyperledger/identus/walletsdk/edgeagent/EdgeAgentTests.kt
edge-agent-sdk/src/commonTest/kotlin/org/hyperledger/identus/walletsdk/edgeagent/PolluxMock.kt

We are changing from our rust uniffi [anoncreds library](https://github.com/input-output-hk/anoncreds-rs) to the Aries uniffi [anoncreds library](https://github.com/hyperledger/aries-uniffi-wrappers)

refactor: change anoncreds library to aries uniffi

---

edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/domain/models/Errors.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/domain/models/MessageAttachment.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/edgeagent/EdgeAgent.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/edgeagent/EdgeAgentError.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/edgeagent/protocols/outOfBand/OutOfBandInvitation.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/edgeagent/protocols/proofOfPresentation/Presentation.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/edgeagent/protocols/proofOfPresentation/ProposePresentation.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/edgeagent/protocols/proofOfPresentation/RequestPresentation.kt
edge-agent-sdk/src/commonTest/kotlin/org/hyperledger/identus/walletsdk/edgeagent/EdgeAgentTests.kt
sampleapp/src/main/java/org/hyperledger/identus/walletsdk/sampleapp/ui/contacts/ContactsViewModel.kt
sampleapp/src/main/res/values/strings.xml

This PR brings contactless presentation request to the kmm SDK.
The OOB is taken as usual but when it contains a presentation request it takes a different route to verify is not expired, verifies all required fields are there and stores the request presentation so the user can display the request to the end user.

feat: contactless presentation request

---

README.md
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/edgeagent/EdgeAgent.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/edgeagent/mediation/BasicMediatorHandler.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/edgeagent/protocols/pickup/PickupRunner.kt
edge-agent-sdk/src/commonMain/kotlin/org/hyperledger/identus/walletsdk/pollux/models/AnonCredential.kt

This PR remediates the lack of commits with breaking changes messages. We noticed no commit with breaking change contains that as part of the PR message leading to the semantic release not being able to bump the version accordingly.
Also used the PR to add a fix to en issue found by QA on the anoncred verification flow.
BREAKING CHANGE:
Pollux Module
- `restoreCredential` now requires a third parameter `revoked`.
- Removed: `createVerifiablePresentationJWT`, `createVerifiablePresentationAnoncred`, `getCredentialDefinition`, and `getSchema`.
- Added new method: `processCredentialRequestSDJWT`.
- `PolluxImpl` now implements `processCredentialRequestSDJWT`.
- Pollux methods `parseCredential` and `processCredentialRequestAnoncreds` now accept `linkSecret: String` instead of `linkSecret: …

fix: anoncred verification and breaking changes missing

---

build.gradle.kts

Removes the sign when publishing to maven local

chore: disable artifact sign for local builds

---

build.gradle.kts
gradle.properties

Signed-off-by: Cristian G <cristian.castro@iohk.io>
Release flow fails: 
`Failed to remove private key due to: The process '/usr/bin/gpg' failed with exit code 2`.
This error was seen on apollo release and resolved. Used the same commit to update the release flow for kmp but found something that was not included correctly.

fix: release 4.0

---

build.gradle.kts
edge-agent-sdk/build.gradle.kts
gradle.properties

fix: gradle artifact signing

---

tests/end-to-end/README.md

chore: update e2e test readme

---

.github/workflows/e2e-tests.yml
.releaserc.yml
tests/end-to-end/build.gradle.kts
tests/end-to-end/notes

Updates sdk to latest version for sdk
Removes notes from git
Fixes release dependency update

test: small e2e enhancements
